# BASE DE DATOS LOCAL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/asistente}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# GROQ IA
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions